gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries

.travis.yml
README.md
requirements.txt

~Once coveralls works, I'm going to add a coverage badge to READMD.md~
Closes #100

Coveralls integration

---

mainapp/tests.py
map/tests.py
search/tests.py
signup/tests.py

- Our current test coverage: [59%](https://coveralls.io/github/gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries?branch=develop)
- After this PR: [69%](https://coveralls.io/github/gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries?branch=testcoverage)
- Now we have good coverage except the cases we call external API such as craigslist, 311, etc.

Add testcases

---

.travis.yml
requirements.txt

Black behaves in a different way by their version, especially for 19.3 and 19.10.

Fix black version to 19.3b0

---

mainapp/templates/account/login.html
mainapp/templates/account/signup.html

Added back button on signup and login page.

Back Button

---

location/templates/location.html

delete duplicate apartment section

---

mainapp/templates/index.html

- performed validation for search field to only allow 5 digit zipcodes

Minor fix for search field on homepage

---

mainapp/templates/account/login.html
mainapp/templates/account/signup.html

Hey, the issue has been fixed.

Back button2

---

release-tasks.sh

This PR fixes the deployment issue on the heroku instance

Do not run loaddata for the production

---

citystreets/settings.py
location/forms.py
location/templates/apartment.html
location/tests.py
location/urls.py
location/views.py
mainapp/templates/index.html

This PR closes #208 
- If a landlord is set in the apartment model, an "Interested?" button is displayed that allows the renter to contact the landlord.
- Clicking the "Interested?" button brings up a popup window
- Email is sent to the landlord from "fivefries8@gmail.com"
- Email includes the renter's name, email and a link to the apartment that the renter is interested in
- Includes test coverage

Apply for Apartment (Contact Landlord)

---

location/templates/location.html

Fixed minor display issue where the button for Write a Review in the location page was displaying as editable.

Fixed editable Review Button

---

location/views.py

fixed bug not assigning description and landlord when apartment was created

Bug fix apartment upload

---

external/res/fetch.py

Removed nan from Restaurants Data.

Removed nan from Restaurants Data

---

location/templates/apartment.html
location/templates/apartment_update.html
location/templates/claim.html
location/templates/location.html
mainapp/static/css/styles.css
mainapp/templates/base.html

Add breadcrumbs

---

location/templates/apartment.html
location/templates/apartment_update.html
location/templates/claim.html
location/templates/claim_result.html
location/templates/location.html
location/tests.py
location/urls.py
location/views.py
mainapp/templates/account.html

Updates our URLs, templates, and tests to use the apartment primary key instead of suite_num.

Apartment ID Fix

---

external/googleapi/g_utils.py
external/models.py

Attempts to guard against the issue where a CachedSearch gets saved without a lat or lon value.

Missing lat/lon bug

---

search/templates/search/results_311.html

- Not sure if it's super important but I think it's good for readability. Otherwise the user is overwhelmed by a lot of information at once.

Added hide/display complaints button

---

search/views.py

- Fixes search bugs when querying 100100, 12111, "fgfgfg" etc.

Search bug fix

---

search/templates/search/search.html
search/templatetags/custom_tags.py

Bug fix for displaying too many pages

Pagination bug

---

requirements.txt

Fixes issue where upgrading to django 3.0 breaks dependencies.

pinned django version

---

location/templates/apartment.html
location/templates/location.html
location/tests.py
location/views.py

This PR brings out the hidden functionality of the website.
- Shows favorite/unfavorite functionality to user. User is redirected to login and brought back to the same page after login.
- Displays "write a review" as a modal window.
- Handles the following cases for "write a review"
1. Not logged in -- redirect to login
2. Not a tenant -- instructions for becoming a tenant
3. Else -- displays review form
- Displays "Interested?" button always
- Handles the following cases:
1. Not logged in -- redirect to login
2. Apartment has no landlord -- instructions for becoming a landlord
3. Landlord = user -- can't contact yourself message
4. Else -- displays contact landlord form
- Added confirmation message after sending email to landlord

Improves overall website flow

---

cli/fetch_geocode.py
cli/normalize_us_address.py
requirements.txt
search/views.py

- Closes #303 
- Currently, it searches only with city, state, zip code
- This PR adds street address to the search parameter

Search with street as well

---

location/forms.py
location/tests.py

I forgot to add a negative suite number check in the apartment update form. This fixes that oversight.

added missing negative suite validation

---

location/templates/location.html
mainapp/static/css/styles.css

This PR changes the styling on the location page.
- Created an account for font awesome library so we can use the CDN instead of downloading all the files
- Changed favorites icon to a heart and removed borders around the button
- Positioned favorites and review buttons inline with the title
- Placed average rating inline with "Reviews"

Location page styling part 1

---

location/templates/apartment.html
location/templates/apartment_update.html
location/templates/location.html
mainapp/static/css/styles.css
mainapp/static/js/project.js
mainapp/templates/base.html
mainapp/templates/index.html
mainapp/templates/nav.html
search/templates/search/search.html

added bootstrap.js import to nav so the messages can be closed from anywhere and moving script imports to bottom of body to improve load times.
Also made the alert float above the top of the page and added an auto-close after 5 seconds.

Alert Message UX Updates

---

location/models.py
location/templates/favlist.html
mainapp/static/css/styles.css
search/templates/search/search.html
search/tests.py
search/views.py

- Closes #329
- Revises the style of cards
- Also makes pagination centered

Show favorites as cards

---

location/templates/claim.html
location/templates/location.html
mainapp/templates/account.html
mainapp/templates/index.html
mainapp/templates/nav.html
search/templates/search/search.html

Fixed JS Import issue and cleaned up JS imports and CSS imports

Fixed JS Import Issue

---

search/templates/search/search.html

This PR: display price tag in map

display price tag in map

---

mainapp/templates/account.html

Replaced the logout button.
Now: 
Master Branch:

Replaced logout

---

refresh_apartment/views.py

fix empty equation

---

location/templates/location.html

- Closes #220 
- In my opinion, "Apartments" rows are too wide. I plan to add "gallery" where users can see all of the images from apartments under the location.

Location Styling (2)

---

location/templates/favlist.html
mainapp/static/css/styles.css
mainapp/templates/account.html

I'm still working on this but I'm putting the PR out there so people can take a look and give me feedback.
Updates:
Review and Apartment Cards: Copied/modified Yonguk's styling from the Favorite list and Location pages for the Apartment cards and Review cards, respectively.
Changed the Places I live/own into collapsible accordions which are defaulted to collapsed.

Account.html Styling Updates

---

mainapp/templates/account.html
mainapp/templates/nav.html

Added Logout Button in Nav
